CREATE DATABASE CRUDPDO;

USE CRUDPDO;


CREATE TABLE PESSOA(
    `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `NOME` VARCHAR (255),
    `TEFONE` VARCHAR (15),
    `EMAIL` VARCHAR(50),
    PRIMARY KEY(ID)
);